### ISSUE TITLE
ツアーページの修正

### ISSUE THREAD

**Issue by K-shir0** [indoor-m/hotcale#38]
### ツアーページの UI

- 保存ボタン
	- ホバーすると色を若干かえたい
		- 参考になりそう https://tailwindcss.com/docs/hover-focus-and-other-states
	- マウスの形も変えたい
		- 指アイコン

- 削除ボタンが必要
	- 保存ボタンの隣
	- できれば削除しますかのモーダルを表示してからとかにしたい（発表までには間に合わせなくても良い）

- 巡回リンク
	- 入れ替え時（マウスホバー）に選択状態になってしまうので選択状態にならないようにする
		-  これでいけそう？ [User Select - Tailwind CSS](https://tailwindcss.com/docs/user-select)

**Comment by K-shir0** [comment]
@tomatoaas #37  修正中にいくつか気になった点をまとめました。確認お願いします。

**Comment by tomatoaas** [comment]
@K-shir0 
https://tailwindcss.com/docs/cursor
どのカーソルに変更します？
